# Generated by Django 5.0.6 on 2025-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HL7MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_system', models.CharField(blank=True, max_length=50)),
                ('message_type', models.CharField(blank=True, max_length=20)),
                ('raw_hl7', models.TextField()),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('encounter_present', models.BooleanField(default=False)),
                ('x12_length', models.IntegerField(default=0)),
            ],
        ),
    ]
