# Generated by Django 5.0.6 on 2025-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7messagelog',
            name='error_category',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VALIDATION', 'VALIDATION'), ('MAPPING', 'MAPPING'), ('DOWNSTREAM', 'DOWNSTREAM'), ('AUTH', 'AUTH'), ('UNKNOWN', 'UNKNOWN')], db_index=True, default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='has_x12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='patient_class',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('VALIDATED', 'VALIDATED'), ('TRANSFORMED', 'TRANSFORMED'), ('FAILED', 'FAILED')], db_index=True, default='RECEIVED', max_length=16),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
