# Generated by Django 5.2.8 on 2026-01-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_hl7messagelog_error_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7messagelog',
            name='message_profile',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='source_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hl7messagelog',
            name='trigger_event',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hl7messagelog',
            name='error_category',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VALIDATION', 'VALIDATION'), ('MAPPING', 'MAPPING'), ('DOWNSTREAM', 'DOWNSTREAM'), ('AUTH', 'AUTH'), ('SOURCE_SYSTEM', 'SOURCE_SYSTEM'), ('FACILITY_VARIANCE', 'FACILITY_VARIANCE'), ('UNKNOWN', 'UNKNOWN')], db_index=True, default='NONE', max_length=32),
        ),
    ]
