# Generated by Django 5.0.6 on 2026-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_hl7messagelog_message_profile_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['-created_at'], name='example_hl7_created_fee191_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['processing_status', '-created_at'], name='example_hl7_process_0fc2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['message_type', '-created_at'], name='example_hl7_message_47dfb9_idx'),
        ),
    ]
