# Generated by Django 5.0.6 on 2026-01-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_hl7messagelog_example_hl7_created_fee191_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='RECEIVED', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('inserted', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('duplicates_in_file', models.IntegerField(default=0)),
                ('reject_samples', models.JSONField(blank=True, default=list)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=16)),
                ('address1', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
