# Generated by Django 5.2.8 on 2026-03-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_patientimportrun_patientrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('claim_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('patient_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('PARTIAL', 'Partial Payment'), ('DENIED', 'Denied'), ('PENDING', 'Pending')], db_index=True, default='SUBMITTED', max_length=16)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('x12_837', models.TextField(blank=True, default='')),
                ('x12_835', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='hl7messagelog',
            name='example_hl7_created_fee191_idx',
        ),
        migrations.RemoveIndex(
            model_name='hl7messagelog',
            name='example_hl7_process_0fc2f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='hl7messagelog',
            name='example_hl7_message_47dfb9_idx',
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['created_at'], name='example_hl7_created_c78065_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['processing_status', 'created_at'], name='example_hl7_process_26d735_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['message_type', 'created_at'], name='example_hl7_message_fba31c_idx'),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='message_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim', to='example.hl7messagelog'),
        ),
        migrations.AddIndex(
            model_name='claimrecord',
            index=models.Index(fields=['status', 'created_at'], name='example_cla_status_9653fd_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrecord',
            index=models.Index(fields=['patient_id', 'created_at'], name='example_cla_patient_343bb2_idx'),
        ),
    ]
