# Generated by Django 5.2.8 on 2026-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_claim_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('fhir_resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('fhir_payload', models.JSONField(default=dict)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=16)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('error_detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='example_web_status_583797_idx'), models.Index(fields=['trace_id'], name='example_web_trace_i_53b3c3_idx')],
            },
        ),
    ]
