# Generated by Django 5.2.8 on 2026-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_webhook_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
