# Generated by Django 5.0.6 on 2025-12-17 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('input_type', models.CharField(choices=[('HL7', 'HL7'), ('JSON', 'JSON'), ('EDI', 'EDI'), ('OTHER', 'OTHER')], default='OTHER', max_length=16)),
                ('output_type', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='RECEIVED', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('error_count', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.TextField()),
                ('parsed_preview', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('step_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], default='OK', max_length=8)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='logtrace.tracelog')),
            ],
            options={
                'ordering': ['sequence'],
                'index_together': {('trace_log', 'sequence')},
            },
        ),
    ]
