# Generated by Django 5.2.8 on 2025-12-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logtrace', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tracestep',
            new_name='tracestep_trace_seq_idx',
            old_fields=('trace_log', 'sequence'),
        ),
    ]
